### PR TITLE
Windows: Fix declaration for C99 and re-enable Gnu.C test.

### PR DESCRIPTION
**Pull request by marsupial**
The test was failing for a reason that likely shouldn't be ignored.

This reverts commit 5947e13cb99052b6f7a5b501244ee2be9be9d080.

### CODE REVIEW

**Comment by bellenot** [comment]
And it's still failing...

**Comment by marsupial** [comment]
Hopefully no longer.

**Comment by bellenot** [comment]
> Remove C++11 test which Visual Studio cannot handle.

And what about the other platforms?

**Comment by marsupial** [comment]
The test is for GNU keywords, having -std=gnu++14 -std=gnu++1z is enough as they test the same mechanism.
-std=gnu++11 really adds nothing but failure for Windows, and fixing for that would mean you're just testing that C++11 cannot run on Windows

If someone feels it is really necessary, then it would probably be best to have a directory devoted to C++11 tests that are not activated on Windows rather than allowing failure all over.

**Comment by bellenot** [comment]
OK, thanks for the explanation @marsupial. If @vgvassilev confirm (and agrees), and if it fixes the test, then it is would be fine with me

**Comment by marsupial** [comment]
Updated again to work-around the Windows issue without dropping it entirely.

**Comment by vgvassilev** [comment]
Looks good to me.

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by ferdymercury** [comment]
Moved to https://github.com/root-project/root/pull/16694

**Pull request closed without merging**
