### PR TITLE
Minor additions / fixes.

### PR DESCRIPTION
**Pull request by marsupial**

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@vgvassilev asked me to hold off with merging the others until he bumped llvm, which according to him should happen still this week.

**Comment by marsupial** [comment]
FWIW I have far more time this week than I will next.

**Comment by marsupial** [comment]
Might be worth getting #135 so CI works properly again.

**Comment by Axel-Naumann** [comment]
LGTM (testing ROOT), but the first commit is already part of PR #139 so I'll skip that. If there is something missing from it (the patch seems to not be a 100% overlap if I interpret git's reaction correctly) then please let me know!

**Comment by marsupial** [comment]
Yes probably just backed out to the wrong place when building get the PR...should be exactly the same.

**Comment by marsupial** [comment]
Yes probably just backed out to the wrong place when building get the PR...change-set should be exactly the same as the one already committed.

**Comment by Axel-Naumann** [comment]
Merged!

**Pull request closed without merging**
